import type { CommunityAuthor, CommunityComment, CommunityPost } from './communityData';

const now = Date.now();
const daysAgo = (days: number) => new Date(now - days * 86_400_000);

const users: CommunityAuthor[] = [
  { id: 'seed_minseo', username: 'minseo01', displayName: '민서', avatarUrl: null },
  { id: 'seed_jihoon', username: 'jihoon_actor', displayName: '지훈', avatarUrl: null },
  { id: 'seed_yerin', username: 'yerin_kim', displayName: '예린', avatarUrl: null },
  { id: 'seed_hyunwoo', username: 'hyunwoo_h', displayName: '현우', avatarUrl: null },
  { id: 'seed_sua', username: 'sua_actress', displayName: '수아', avatarUrl: null },
  { id: 'seed_taeyang', username: 'taeyang_pd', displayName: '태양', avatarUrl: null },
];

export const COMMUNITY_FIXTURE_POSTS: CommunityPost[] = [
  {
    id: '1024',
    boardId: 'free',
    title: '여러분은 왜 연기를 시작하셨어요?',
    body: '처음 시작한 이유가 사람마다 다 다르더라고요. 저는 그냥 무대 위 어떤 사람이 진짜로 살아있는 것 같아서요. 여러분은 어땠나요?',
    score: 18,
    commentCount: 3,
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
    author: users[0],
    anonymous: false,
    myVote: 0,
    isBookmarked: false,
  },
  {
    id: '1019',
    boardId: 'secret',
    title: '그만두고 싶다는 생각이 자주 들어요',
    body: '이게 진짜 내 길인지 모르겠어요. 몇 년을 쏟았는데 아직도 시작점에 서 있는 느낌이고, 주위 사람들 보면 다 자기 자리 잡아가는 것 같아 자꾸 흔들려요.',
    score: 21,
    commentCount: 3,
    createdAt: daysAgo(6),
    updatedAt: daysAgo(6),
    author: users[1],
    anonymous: true,
    myVote: 0,
    isBookmarked: false,
  },
  {
    id: '1011',
    boardId: 'free',
    title: '슬럼프 올 때 어떻게 빠져나오세요?',
    body: '스스로 부족하다는 생각이 들 때마다 한참을 못 움직이겠어요. 여러분만의 방법 있으면 듣고 싶어요.',
    score: 16,
    commentCount: 4,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(10),
    author: users[1],
    anonymous: false,
    myVote: 0,
    isBookmarked: false,
  },
  {
    id: '1031',
    boardId: 'free',
    title: '혼자 대본 읽을 때 어떤 순서로 하세요?',
    body: '장면 분석부터 들어가야 할지, 일단 소리 내서 여러 번 읽어보는 게 좋은지 매번 헷갈려요. 본인만의 루틴 공유해주실 분?',
    score: 4,
    commentCount: 3,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
    author: users[2],
    anonymous: false,
    myVote: 0,
    isBookmarked: false,
  },
  {
    id: '1030',
    boardId: 'free',
    title: '감정을 진짜로 느낀다는 게 뭘까요?',
    body: '기술적으로 흉내 내는 거랑, 그 순간에 진짜로 느끼는 거랑 차이가 있다고 들었는데 그게 정확히 뭐인지 잘 모르겠어요.',
    score: 13,
    commentCount: 4,
    createdAt: daysAgo(8),
    updatedAt: daysAgo(8),
    author: users[4],
    anonymous: false,
    myVote: 0,
    isBookmarked: false,
  },
  {
    id: '1029',
    boardId: 'free',
    title: '발성 연습과 표현 연습, 비중을 어떻게 두세요?',
    body: '둘 다 중요한 건 아는데 시간이 한정되어 있다 보니 매번 비율을 고민하게 돼요.',
    score: 7,
    commentCount: 2,
    createdAt: daysAgo(6),
    updatedAt: daysAgo(6),
    author: users[5],
    anonymous: false,
    myVote: 0,
    isBookmarked: false,
  },
  {
    id: '1028',
    boardId: 'secret',
    title: '비교하는 거 멈추기가 너무 어려워요',
    body: '비교 안 한다고 다짐해도 SNS 한 번만 켜면 무너져요. 다들 어떻게 하세요.',
    score: 14,
    commentCount: 2,
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
    author: users[3],
    anonymous: true,
    myVote: 0,
    isBookmarked: false,
  },
  {
    id: '1027',
    boardId: 'promo',
    title: '여기 비어있네요. 다들 어떤 활동 하고 계세요?',
    body: '홍보 부담스럽지 않게 가볍게 자기 활동 소개부터 시작해보면 어떨까요. 댓글로 한 줄씩이라도.',
    score: 4,
    commentCount: 2,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
    author: users[1],
    anonymous: false,
    myVote: 0,
    isBookmarked: false,
  },
  {
    id: '1026',
    boardId: 'promo',
    title: '혹시 운영하시는 채널이나 블로그 있으세요?',
    body: '유튜브, 인스타, 블로그, 형식 상관없이요. 같은 길 가는 사람들 어떻게 자기 작업 기록하는지 궁금해요.',
    score: 6,
    commentCount: 1,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
    author: users[2],
    anonymous: false,
    myVote: 0,
    isBookmarked: false,
  },
];

export const COMMUNITY_FIXTURE_COMMENTS: CommunityComment[] = [
  {
    id: 'c-1024-1',
    postId: '1024',
    parentId: null,
    body: '저는 처음 무대에서 박수받았을 때 느낌이 잊히지 않더라고요.',
    score: 3,
    createdAt: daysAgo(3),
    deletedAt: null,
    author: users[1],
    anonymous: false,
    myVote: 0,
  },
  {
    id: 'c-1024-2',
    postId: '1024',
    parentId: null,
    body: '딱히 거창한 이유는 없었는데 하다 보니 못 놓겠다는 분도 많은 것 같아요.',
    score: 4,
    createdAt: daysAgo(3),
    deletedAt: null,
    author: users[4],
    anonymous: false,
    myVote: 0,
  },
  {
    id: 'c-1019-1',
    postId: '1019',
    parentId: null,
    body: '주변과 자기 속도가 달라서 더 힘드신 것 같아요. 응원합니다.',
    score: 5,
    createdAt: daysAgo(5),
    deletedAt: null,
    author: users[2],
    anonymous: true,
    myVote: 0,
  },
  {
    id: 'c-1011-1',
    postId: '1011',
    parentId: null,
    body: '운동이 의외로 큰 도움이었어요. 몸이 풀리면 마음도 풀리더라고요.',
    score: 5,
    createdAt: daysAgo(8),
    deletedAt: null,
    author: users[5],
    anonymous: false,
    myVote: 0,
  },
];
