import type { ExcerRoom } from './excerFilters';

const now = Date.now();
const daysAgo = (days: number) => new Date(now - days * 86_400_000);

export const EXCER_FIXTURE_ROOMS: ExcerRoom[] = [
  {
    id: 'fx-001',
    slug: 'hyehwa-coral-studio',
    name: '혜화 코랄 스튜디오',
    region: '종로구 동숭동',
    subway: ['혜화역'],
    lat: 37.5826,
    lng: 127.0019,
    priceHour: 15000,
    priceNote: null,
    hours: { open: '09:00', close: '24:00', days: [0, 1, 2, 3, 4, 5, 6] },
    phone: '02-000-0001',
    bookingUrl: null,
    photos: [],
    mirror: true,
    soundproof: 'strong',
    sizePyeong: 15,
    lighting: 'bright',
    scriptstand: true,
    microphone: false,
    verifiedAt: daysAgo(12),
    createdAt: daysAgo(90),
    updatedAt: daysAgo(12),
    active: true,
  },
  {
    id: 'fx-002',
    slug: 'daehakro-script-lab',
    name: '대학로 스크립트 랩',
    region: '종로구 동숭동',
    subway: ['혜화역', '동대문역'],
    lat: 37.5817,
    lng: 127.0036,
    priceHour: 10000,
    priceNote: null,
    hours: { open: '10:00', close: '23:00', days: [1, 2, 3, 4, 5, 6] },
    phone: '02-000-0002',
    bookingUrl: 'https://example.com/book/daehakro',
    photos: [],
    mirror: true,
    soundproof: 'medium',
    sizePyeong: 10,
    lighting: 'normal',
    scriptstand: true,
    microphone: false,
    verifiedAt: daysAgo(3),
    createdAt: daysAgo(60),
    updatedAt: daysAgo(3),
    active: true,
  },
  {
    id: 'fx-003',
    slug: 'hongdae-mirror-room',
    name: '홍대 미러룸',
    region: '마포구 서교동',
    subway: ['홍대입구역'],
    lat: 37.5571,
    lng: 126.9237,
    priceHour: 20000,
    priceNote: null,
    hours: { open: '10:00', close: '26:00', days: [0, 1, 2, 3, 4, 5, 6] },
    phone: '02-000-0003',
    bookingUrl: 'https://example.com/book/hongdae',
    photos: [],
    mirror: true,
    soundproof: 'strong',
    sizePyeong: 22,
    lighting: 'bright',
    scriptstand: true,
    microphone: true,
    verifiedAt: daysAgo(45),
    createdAt: daysAgo(120),
    updatedAt: daysAgo(45),
    active: true,
  },
  {
    id: 'fx-004',
    slug: 'gangnam-quiet-stage',
    name: '강남 콰이엇 스테이지',
    region: '강남구 역삼동',
    subway: ['역삼역', '강남역'],
    lat: 37.5006,
    lng: 127.0364,
    priceHour: 25000,
    priceNote: null,
    hours: { open: '08:00', close: '24:00', days: [0, 1, 2, 3, 4, 5, 6] },
    phone: '02-000-0004',
    bookingUrl: null,
    photos: [],
    mirror: true,
    soundproof: 'strong',
    sizePyeong: 18,
    lighting: 'normal',
    scriptstand: false,
    microphone: false,
    verifiedAt: daysAgo(70),
    createdAt: daysAgo(200),
    updatedAt: daysAgo(70),
    active: true,
  },
  {
    id: 'fx-005',
    slug: 'sungshin-small-stage',
    name: '성신여대 소극장 연습실',
    region: '성북구 동선동',
    subway: ['성신여대입구역'],
    lat: 37.5928,
    lng: 127.0163,
    priceHour: 8000,
    priceNote: null,
    hours: { open: '11:00', close: '22:00', days: [1, 2, 3, 4, 5] },
    phone: '02-000-0005',
    bookingUrl: null,
    photos: [],
    mirror: false,
    soundproof: 'medium',
    sizePyeong: 8,
    lighting: 'dim',
    scriptstand: true,
    microphone: false,
    verifiedAt: daysAgo(5),
    createdAt: daysAgo(30),
    updatedAt: daysAgo(5),
    active: true,
  },
];
